### ISSUE TITLE
Error: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by sistemasnegros** [fumail/fuglu#94] opened 2017-07-07 13:12 UTC
ERROR Could not commit message. Error: 'ascii' codec can't decode byte 0xc3 in position 2804: ordinal not in range(128)

solution in .decode('utf-8')

i don't know in which linea

**Comment by gryphius** [comment] 2017-07-07 13:15
Thanks for your report. Could you post the the full exception, it should be available in  `fuglu.log` or potentially by running `fuglu_control exceptionlist`. Also, if you have the original message sample that caused this and are allowed to provide it this would be helpful.

**Comment by sistemasnegros** [comment] 2017-07-07 13:47
detected the problem when the emails has accent. (spanish)
example:
body: pruebá

**Comment by sistemasnegros** [comment] 2017-07-07 13:49
2017-07-07 09:44:47,658 fuglu.SessionHandler: ERROR Could not commit message. Error: 'ascii' codec can't decode byte 0xc3 in position 663: ordinal not in range(128)
2017-07-07 09:44:47,667 fuglu.SessionHandler: WARNING DEFERRED 2e82c3b48a73425a9a18089d0843c925

**Comment by sistemasnegros** [comment] 2017-07-07 13:52
this version has the error
0.6.6-65-g14900f6 running

not has this problem
0.6.6-48-gfe834ae

**Comment by gryphius** [comment] 2017-07-07 13:58
thank you, I'll look into this ASAP , hopefully this weekend

**Comment by gryphius** [comment] 2017-07-08 05:09
I wasn't able to reproduce in my test environment so far (I might have to set up a full after-queue setup, I don't have one available right now).

if you still have a system running where the error happened, could you give me the output of
`fuglu_control exceptionlist` ?

Also it would be helpful to know your configuration (`fuglu_conf -n`)

Also, could you attach a message (`.eml` file) which causes this problem?

**Comment by sistemasnegros** [comment] 2017-07-08 18:49
hi,

I was testing,
I try on another server the same fuglu version and the accents work.
I do not know why I did not work yesterday, I do not know what problem I have with the coding

**Comment by sbuckmann** [comment] 2017-07-23 18:51
Same problem here (Switzerland; German Umlauts). Ran fine around a week before.
fuglu_control exceptionlist shows nothing.
fuglu_conf -n throws an exception:
> Traceback (most recent call last):
>   File "/usr/local/bin/fuglu_conf", line 250, in <module>
>     activeconfig = cloneConfig(userconfig)
>   File "/usr/local/bin/fuglu_conf", line 50, in cloneConfig
>     config.write(tmpfile)
>   File "/usr/lib/python2.7/dist-packages/configparser.py", line 955, in write
>     self._sections[section].items(), d)
>   File "/usr/lib/python2.7/dist-packages/configparser.py", line 959, in _write_section
>     fp.write(u"[{0}]\n".format(section_name))
> TypeError: 'unicode' does not have the buffer interface

fuglu --lint gives no error:
> Fuglu 0.6.6
> ---------- LINT MODE ----------
> Checking dependencies...
> sqlalchemy: not installed Optional dependency, required if you want to enable any database lookups
> BeautifulSoup: not installed Optional dependency, this improves accuracy for stripped body searches in filters - not required with a default config
> magic: found python-file/libmagic bindings (http://www.darwinsys.com/file/)
> Loading extensions...
> fuglu.extensions.sql: disabled (sqlalchemy not installed)
> Loading plugins...
> Plugin loading complete
> Linting  main configuration
> OK
> 
> Linting  sql configuration
> Failed sql extension not enabled
> 
> Linting Plugin  Plugin Skipper Config section: PluginSkipper
> OK
> 0 plugins reported errors.
> 
> Checking logging configuration....
> OK

```

**Comment by gryphius** [comment] 2017-07-23 20:11
Could you share your fuglu.conf and if possible a sample message? Do you see a traceback in fuglu's log? The error from fuglu --lint seems to be a different (but possibly related) problem. 

Dankä :)

On July 23, 2017 8:51:35 PM GMT+02:00, Stefan Buckmann <notifications@github.com> wrote:
>Same problem here (Switzerland; German Umlauts). Ran fine around a week
>before.
>fuglu_control exceptionlist shows nothing.
>fuglu_conf -n throws an exception:
>> Traceback (most recent call last):
>>   File "/usr/local/bin/fuglu_conf", line 250, in <module>
>>     activeconfig = cloneConfig(userconfig)
>>   File "/usr/local/bin/fuglu_conf", line 50, in cloneConfig
>>     config.write(tmpfile)
>>   File "/usr/lib/python2.7/dist-packages/configparser.py", line 955,
>in write
>>     self._sections[section].items(), d)
>>   File "/usr/lib/python2.7/dist-packages/configparser.py", line 959,
>in _write_section
>>     fp.write(u"[{0}]\n".format(section_name))
>> TypeError: 'unicode' does not have the buffer interface
>
>fuglu --lint gives no error:
>> Fuglu 0.6.6
>> ---------- LINT MODE ----------
>> Checking dependencies...
>> sqlalchemy: not installed Optional dependency, required if you want
>to enable any database lookups
>> BeautifulSoup: not installed Optional dependency, this improves
>accuracy for stripped body searches in filters - not required with a
>default config
>> magic: found python-file/libmagic bindings
>(http://www.darwinsys.com/file/)
>> Loading extensions...
>> fuglu.extensions.sql: disabled (sqlalchemy not installed)
>> Loading plugins...
>> Plugin loading complete
>> Linting  main configuration
>> OK
>> 
>> Linting  sql configuration
>> Failed sql extension not enabled
>> 
>> Linting Plugin  Plugin Skipper Config section: PluginSkipper
>> OK
>> 0 plugins reported errors.
>> 
>> Checking logging configuration....
>> OK
>
>```
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gryphius/fuglu/issues/94#issuecomment-317273763

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gryphius** [comment] 2017-07-23 20:14
I meant error from fuglu_conf obviously.

**Comment by sbuckmann** [comment] 2017-07-24 15:09
fuglu.conf and a mail that can't be sent are attached.

[Mail.eml.txt](https://github.com/gryphius/fuglu/files/1170235/Mail.eml.txt)
[fuglu.conf.txt](https://github.com/gryphius/fuglu/files/1170234/fuglu.conf.txt)

**Comment by gryphius** [comment] 2017-07-25 07:12
@sbuckmann thank you. I'm still trying reproduce the problem in a standard fuglu setup. Interestingly, your 'fuglu --lint' says you're running a standard 0.6.6 (not a version from git), if that's true then this wasn't introduced by a recent code commit. I wonder if the database config has something do do with it. 

@sistemasnegros are you running fuglu on mailcow as well? Could you post your `fuglu.conf` as well please with  private data like database usernames/passwords replaced with asterisks.

**Comment by gryphius** [comment] 2017-07-25 07:40
also, if any of you has additional config files in /etc/fuglu/conf.d , please share them as well

**Comment by gryphius** [comment] 2017-07-25 10:16
I have added improved logging in https://github.com/gryphius/fuglu/commit/723177cf29a36d7de5c0a3d2c93255860cb8f8a0 . Errors in that region for some reason got logged to stdout instead of the standard log target. 
It would be helpful if you could update and post the resulting tracke from fuglu's log when the error happens again

**Comment by sbuckmann** [comment] 2017-07-25 13:25
I do not have any additional configs in /etc/fuglu/conf.d.
I added the changes from [723177c](https://github.com/gryphius/fuglu/commit/723177cf29a36d7de5c0a3d2c93255860cb8f8a0), restarted fuglu and tried to send a mail containing german umlauts. Log:

> 
> 2017-07-25 15:19:07,130 root        : INFO FuGLU Version 0.6.6 starting up
> 2017-07-25 15:19:07,134 fuglu.MainController: INFO Init Stat Engine
> 2017-07-25 15:19:07,135 fuglu.MainController: INFO Init Threadpool
> 2017-07-25 15:19:07,136 fuglu.MainController: INFO Starting interface sockets...
> 2017-07-25 15:19:07,136 fuglu.MainController: INFO starting connector esmtp/10025
> 2017-07-25 15:19:07,143 fuglu.smtp.incoming.10025: INFO ESMTP Server running on port 10025
> 2017-07-25 15:19:07,144 fuglu.MainController: INFO Startup complete
> 2017-07-25 15:19:07,144 fuglu.control.fuglu_control.sock: INFO Control/Info Server running on port /tmp/fuglu_control.sock                                                                   
> 2017-07-25 15:20:26,668 fuglu.suspectfilter: INFO Reloading Rulefile /etc/fuglu/skipplugins.regex                                                                                            
> 2017-07-25 15:20:26,669 fuglu.SessionHandler: INFO Suspect d29e6b5cd1154381952ef1cd9ae3974b from=xxx@xxx to=yyy@yyy size=790 spam=no virus=no modified=no decision=DUNNO                                                                                                                                                                                           
> 2017-07-25 15:20:26,670 fuglu.SessionHandler: ERROR Could not commit message. Error: Traceback (most recent call last):                                                                      
>   File "/usr/local/lib/python2.7/dist-packages/fuglu/scansession.py", line 118, in handlesession
>     self.protohandler.commitback(suspect)
>   File "/usr/local/lib/python2.7/dist-packages/fuglu/connectors/esmtpconnector.py", line 94, in commitback
>     injectcode, injectanswer = self.re_inject(suspect)
>   File "/usr/local/lib/python2.7/dist-packages/fuglu/connectors/esmtpconnector.py", line 69, in re_inject
>     msgcontent = buildmsgsource(suspect)
>   File "/usr/local/lib/python2.7/dist-packages/fuglu/connectors/esmtpconnector.py", line 48, in buildmsgsource
>     modifiedtext = newheaders + origmsgtxt
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 775: ordinal not in range(128)
> 
> 2017-07-25 15:20:26,671 fuglu.SessionHandler: WARNING DEFERRED d29e6b5cd1154381952ef1cd9ae3974b

**Comment by gryphius** [comment] 2017-07-25 19:57
thanks @sbuckmann , this pinpoints the exact location where the crash is happening. I still haven't been able to reproduce it tho :(

**Comment by micky7** [comment] 2018-03-27 10:14
is there any progress on the bug. I have the same error when using german umlaut like ä,ö,ü,....

**Comment by gryphius** [comment] 2018-03-28 07:45
I have never been able to reproduce this bug in a standard fuglu setup. Do you run fuglu in mailcow as well?  Please provide more information about your setup ( environment, fuglu version, configuration, pre-queue or postqueue, exact errormessage/trace if available). There have been quite a few changes in the git HEAD for the new python3 compatibilty. So we should find out if this is actually the same issue or a similar one that has been newly introduced.

**Comment by micky7** [comment] 2018-03-28 07:56
Yes it is also a mailcow setup. They use the version 0.6.6. 
I have now used the actual sources of github. With the latest changes in github the error is solved.

**Comment by gryphius** [comment] 2018-03-28 09:51
great! in that case I'll close the issue .  @sistemasnegros  / @sbuckmann , can you confirm that updating fuglu fixes the issue for you as well?

**Comment by sbuckmann** [comment] 2018-03-28 15:15
I migrated from mailcow to mailcow-dockerized, so I'm unable to confirm.

**Closed** 2018-03-28 17:35 UTC
Labels: bug
